project:
  type: website
  output-dir: docs

website:
  title: "Alan.dev"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Talks"
        href: talks.qmd
      - text: "About"
        href: about.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true